export type ThemePresetId = 'neutral' | 'warm' | 'rainy-mystery' | 'dark-horror'
export type AppearanceMode = 'dark' | 'light'
export type IllustrationStylePresetId = 'unconstrained' | 'realistic-cinematic' | 'anime' | 'manga' | 'watercolor' | 'oil-painting' | 'pixel-art' | 'custom'
export type ReferenceStyleMode = 'project' | 'reference'
export type ContextBudget = 'standard' | 'long' | 'full'

export interface WritingInstructionSection {
  id: string
  title: string
  content: string
  tags: string[]
  priority: number
}

export interface WritingStyleSample {
  sceneType: string
  content: string
}

export interface WritingInstructionsStructure {
  core: string
  sections: WritingInstructionSection[]
  styleSamples: WritingStyleSample[]
}

export interface StoryProject {
  id: string
  title: string
  themeId: ThemePresetId
  activeChapterId?: string
  autoIllustrate: boolean
  writingInstructions?: string
  writingStructure?: string
  contextBudget?: ContextBudget
  createdAt: number
  updatedAt: number
  lastOpenedAt: number
}

export type MessageKind = 'user' | 'notice' | 'prose' | 'illustration'

export interface ConversationMessage {
  id: string
  projectId: string
  chapterId?: string
  kind: MessageKind
  order: number
  createdAt: number
  text?: string
  paragraphs?: string[]
  title?: string
  illustrationId?: string
  status?: 'ready' | 'pending' | 'failed'
}

export type ParagraphSourceType = 'message' | 'chapter'

/**
 * A stable storage record for a paragraph. Message rendering intentionally
 * continues to use ConversationMessage.paragraphs for backward compatibility.
 */
export interface StoredParagraph {
  id: string
  projectId: string
  sourceType: ParagraphSourceType
  messageId?: string
  chapterId: string
  index: number
  text: string
  fingerprint: string
  createdAt: number
}

export type FeedbackScope = 'message' | 'paragraph'
export type FeedbackVerdict = 'up' | 'down'

/**
 * A durable reader judgement bound to one prose message or one exact stored
 * message paragraph. `targetKey` is a canonical, unique storage key and is
 * generated by the database API rather than supplied by callers.
 */
export interface Feedback {
  id: string
  projectId: string
  messageId: string
  chapterId: string
  scope: FeedbackScope
  paragraphId?: string
  paragraphIndex?: number
  paragraphFingerprint?: string
  targetKey: string
  verdict: FeedbackVerdict
  reason?: string
  customNote?: string
  createdAt: number
  updatedAt: number
}

/** Identifies a feedback target with the current paragraph anchor when needed. */
export interface FeedbackTargetInput {
  projectId: string
  messageId: string
  chapterId: string
  scope: FeedbackScope
  paragraphId?: string
  paragraphIndex?: number
  paragraphFingerprint?: string
}

export interface FeedbackInput extends FeedbackTargetInput {
  verdict: FeedbackVerdict
  reason?: string
  customNote?: string
}

export type UpsertFeedbackInput = FeedbackInput

export interface WritingCharacterPlan {
  name: string
  role: string
  ageAndBuild: string
  fixedTraits: string[]
  defaultLook: string
  wardrobe: string
}

export interface VisualPlan {
  title: string
  prompt: string
  stylePrompt: string
  negativePrompt: string
  characters: WritingCharacterPlan[]
}

/** A durable foreshadowing record. Its id is generated by the application, never by the model. */
export interface Foreshadowing {
  id: string
  text: string
  aliases?: string[]
}

interface SceneNoteFacts {
  time?: string
  location?: string
  povCharacter?: string
  charactersPresent: string[]
  events: string[]
  stateChanges: Array<{ character: string; aspect: string; state: string }>
  relationshipChanges: string[]
  knowledgeChanges: Array<{ character: string; nowKnows: string }>
  unresolvedThreads: string[]
}

/** Persisted scene memory. Resolutions are stable ids, never matching prose. */
export interface SceneNotes extends SceneNoteFacts {
  foreshadowingPlanted: Foreshadowing[]
  resolvedForeshadowingIds: string[]
  /** Old text-only resolutions that could not be safely bound to one open record. */
  legacyUnmatchedResolvedForeshadowingTexts?: string[]
}

/** Parsed model output before persistence. New foreshadowings intentionally have no model-supplied id. */
export interface WritingSceneNotes extends SceneNoteFacts {
  newForeshadowingTexts: string[]
  resolvedForeshadowingIds: string[]
  /** Compatibility input from the obsolete text-only `clues_resolved` response field. */
  legacyResolvedForeshadowingTexts?: string[]
}

export interface WritingTurnResult {
  assistantNote: string
  chapterAction: 'continue' | 'new'
  chapterTitle?: string
  paragraphs: string[]
  chapterSummary?: string
  sceneNotes?: WritingSceneNotes
  visualPlan?: VisualPlan
}

export interface Chapter {
  id: string
  projectId: string
  title: string
  order: number
  content: string
  status: 'draft' | 'final'
  summary?: string
  createdAt: number
  updatedAt: number
}

export type SummaryVersionReason = 'generation' | 'migration' | 'restore'

/**
 * Immutable provenance for a chapter summary. A restore always creates a new
 * record so earlier versions remain auditable.
 */
export interface SummaryVersion {
  id: string
  projectId: string
  chapterId: string
  version: number
  summary: string
  sourceContentHash: string
  sourceParagraphIds: string[]
  reason: SummaryVersionReason
  restoredFromId?: string
  createdAt: number
}

export interface CharacterAsset {
  id: string
  projectId: string
  name: string
  role: string
  identity: {
    ageAndBuild: string
    fixedTraits: string[]
  }
  appearance: {
    defaultLook: string
    wardrobe: string
  }
  continuity: {
    referenceImageUrl?: string
    localUri?: string
    revision: number
    referenceStyleMode?: ReferenceStyleMode
  }
  portraitStatus: 'planned' | 'generating' | 'review' | 'failed' | 'confirmed'
  portraitError?: string
  status: 'draft' | 'confirmed'
  createdAt: number
  updatedAt: number
}

export interface IllustrationAsset {
  id: string
  projectId: string
  chapterId?: string
  messageId?: string
  title: string
  prompt: string
  sceneStylePrompt?: string
  sceneNegativePrompt?: string
  referenceCharacterIds: string[]
  imageUrl?: string
  localUri?: string
  status: 'planned' | 'generating' | 'ready' | 'failed'
  errorMessage?: string
  createdAt: number
  updatedAt: number
}

export interface ProjectStyle {
  id: string
  projectId: string
  presetId: ThemePresetId
  illustrationStyleId: IllustrationStylePresetId
  customVisualPrompt?: string
  visualPrompt: string
  negativePrompt: string
  updatedAt: number
}

export interface ProjectWorkspace {
  project: StoryProject
  messages: ConversationMessage[]
  chapters: Chapter[]
  characters: CharacterAsset[]
  illustrations: IllustrationAsset[]
  style?: ProjectStyle
}
